### ISSUE TITLE
`Error: Authenticate` when running `twilio infra:deploy`

### ISSUE THREAD

**Issue by vernig** [twilio-infra-as-code/outbound-messaging#2]
**Step to reproduce:** 

* Clone example
* Install dependency 
* Set the following variables: 
  * `CHAT_SERVICE_SID=IS4172667fabe14641xxxxx`
  * `FLEX_WORKSPACE_SID=WS541570c274xxxxx`
  * `SMS_TASK_CHANNEL_SID=TCff40977a2ffbxxxxx`
  * `EVERYONE_TASK_QUEUE_SID=WQ461f1b6c3cdbxxxxx`
  * `TWILIO_PHONE_NUMBER=+4477xxxxxxx`
  * `FLEX_PROXY_SERVICE_SID=KSa627ae9638xxxxxxx`
* Execute `twilio infra:deploy`

**Output**

```shell 
Error: Authenticate
        at ServicePage.Page.processResponse (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/base/Page.js:156:11)
        at ServicePage.Page (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/base/Page.js:16:22)
        at new ServicePage (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/rest/serverless/v1/service.js:419:30)
        at Function.<anonymous> (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/rest/serverless/v1/service.js:253:24)
        at Promise_then_fulfilled (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:766:44)
        at Promise_done_fulfilled (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:835:31)
        at Fulfilled_dispatch [as dispatch] (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:1229:9)
        at Pending_become_eachMessage_task (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:1369:30)
        at RawTask.call (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/asap/asap.js:40:19)
        at flush (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/asap/raw.js:50:29)
 
    error: Running program '/Users/gverni/dev/github/twilio-infra/outbound-messaging/src/resources' failed with an unhandled exception:
    Error: Authenticate
        at ServicePage.Page.processResponse (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/base/Page.js:156:11)
        at ServicePage.Page (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/base/Page.js:16:22)
        at new ServicePage (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/rest/serverless/v1/service.js:419:30)
        at Function.<anonymous> (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/twilio/lib/rest/serverless/v1/service.js:253:24)
        at Promise_then_fulfilled (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:766:44)
        at Promise_done_fulfilled (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:835:31)
        at Fulfilled_dispatch [as dispatch] (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:1229:9)
        at Pending_become_eachMessage_task (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/q/q.js:1369:30)
        at RawTask.call (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/asap/asap.js:40:19)
        at flush (/Users/gverni/dev/github/twilio-infra/outbound-messaging/node_modules/asap/raw.js:50:29)
```

**Considerations:** 
This is caused by this line (i.e. commenting it, the error is not happening): 

https://github.com/twilio-infra-as-code/outbound-messaging/blob/b14ad83b192d6a14631dcd59af841cf8e2c41a36/src/resources/index.ts#L7

**Comment by vernig** [comment]
@kaiquelupo this is the issue I ran into. Let me know if I'm doing something wrong / missing any step

**Comment by vernig** [comment]
This will be fixed by https://github.com/twilio-infra-as-code/twilio-pulumi-provider/issues/4. As Workaround, set the `TWILIO_AUTH_TOKEN` manually, e.g. (on macOs): 

```
export TWILIO_AUTH_TOKEN=xxxxxxxxx
````
